### ISSUE TITLE
Mautic won't start after install + cache clear

### ISSUE THREAD

**Issue by travis139** [stars05/mautic-mailgun-mailer-plugin#1]
Hey there, I'm trying to use this plugin with Mautic 3.1.2 and PHP 7.3.

After unpacking the repo into /mautic/plugins/MauticMailgunMailerBundle and clearing /mautic/var/cache I get a "The site is currently offline" error with no logs in /mautic/var/logs to give any details as to what's going wrong.

I renamed the bundle, retried, and Mautic starts just fine without the plugin.

It's definitely not a permissions issue, either. After clearing the cache, I rewrote permission on /var/cache to no avail.

Any ideas?

**Comment by stars05** [comment]
@travis139 And there is no errors in var/logs?
I will try to find a problem.

**Comment by travis139** [comment]
Nothing in /var/logs

That is correct.

**Comment by travis139** [comment]
mod_fcgid: stderr: Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Parse error: syntax error, unexpected 'c2d7a6e05441c4240cee3e8e4605' (T_STRING), expecting ']' - in file /home/trh/alkainstitute.com/mautic/plugins/MauticMailgunMailerBundle/Config/config.php - at line 48

**Comment by travis139** [comment]
>mod_fcgid: stderr: Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Parse error: syntax error, unexpected 'c2d7a6e05441c4240cee3e8e4605' (T_STRING), expecting ']' - in file /home/trh/alkainstitute.com/mautic/plugins/MauticMailgunMailerBundle/Config/config.php - at line 48

I'm

**Comment by travis139** [comment]
I'm a Github noob and tired, didn't mean to close the issue.

**Comment by stars05** [comment]
@travis139 try to update plugin, I’ve updated code and fixed some bugs

**Comment by travis139** [comment]
I just tried the newest code and am experiencing the same issue. There's still nothing relevant in /var/logs.

**Comment by travis139** [comment]
Let me know if I can grab info from other places to help. I can work my way around coding and CLI but it's not my forte.

**Comment by stars05** [comment]
@travis139 yes sure you can ask anyone to help you.

**Comment by travis139** [comment]
@stars05 

What I meant was that I'm willing to help debug my issue, but that I'm not experienced enough to know where to look / what to look for, by myself. If you or someone else could offer assistance in debugging, I could get whatever relevant info for you.

**Comment by f0ns** [comment]
Hello,

I am experiencing the same issue.

Just checked [mautic_root]/var/log and these are the errors we get:

`mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 6 passed to MauticPlugin\MauticMailgunMailerBundle\Swiftmailer\Transport\MailgunApiTransport::__construct() must be of the type string, null given, called in /var/www/mautic/var/cache/prod/Container4eeyoid/getMautic_Transport_MailgunApiService.php on line 8" at /var/www/mautic/plugins/MauticMailgunMailerBundle/Swiftmailer/Transport/MailgunApiTransport.php line 56 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 6 passed to MauticPlugin\\MauticMailgunMailerBundle\\Swiftmailer\\Transport\\MailgunApiTransport::__construct() must be of the type string, null given, called in /var/www/mautic/var/cache/prod/Container4eeyoid/getMautic_Transport_MailgunApiService.php on line 8 at /var/www/mautic/plugins/MauticMailgunMailerBundle/Swiftmailer/Transport/MailgunApiTransport.php:56)"} []
`

`mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function get() on null in /var/www/mautic/app/bundles/CoreBundle/Controller/CommonController.php:196 Stack trace: #0 /var/www/mautic/app/bundles/CoreBundle/Controller/ExceptionController.php(122): Mautic\CoreBundle\Controller\CommonController->delegateView(Array) #1 /var/www/mautic/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\CoreBundle\Controller\ExceptionController->showAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\Debug\Exception\FlattenException), Object(Symfony\Bridge\Monolog\Logger)) #2 /var/www/mautic/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 2) #3 /var/www/mautic/app/bundles/CoreBundle/EventListener/ExceptionListener.php(76): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\R - in file /var/www/mautic/app/bundles/CoreBundle/Controller/CommonController.php - at line 196`

**Comment by stars05** [comment]
@f0ns Hi.
You need to define your webhook api key as string in configuration file in Config/config.php 
It’s must be as string, not null.
Current version of plugin has an empty string.

**Comment by MartinMikita** [comment]
I have the same problem.

After unzipping the repository content into `plugins/MauticMailgunMailerBundle/`, and clear `var/cache/`, our Mautic web stops working. The onle error it gives is `Too many redirects`.

Without clearing `var/cache` (or restoring the backup), the Mautic web is running, but the plugin cannot be detected.

I have filled our `webhook_signing_key`, but we do not want to use webhooks.

**Comment by stars05** [comment]
> I have the same problem.
> 
> After unzipping the repository content into `plugins/MauticMailgunMailerBundle/`, and clear `var/cache/`, our Mautic web stops working. The onle error it gives is `Too many redirects`.
> 
> Without clearing `var/cache` (or restoring the backup), the Mautic web is running, but the plugin cannot be detected.
> 
> I have filled our `webhook_signing_key`, but we do not want to use webhooks.

Do you have any log in var/logs?
